# Generated by Django 4.2.7 on 2024-07-22 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='category',
            field=models.CharField(blank=True, default='未分類', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='todolist',
            name='priority',
            field=models.CharField(choices=[('High', '高'), ('Medium', '中'), ('Low', '低')], default='High', max_length=10),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
