# Generated by Django 4.2.7 on 2024-07-22 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0002_alter_todolist_category_alter_todolist_priority_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='category',
            field=models.CharField(blank=True, default='未分類', max_length=255),
        ),
    ]
