# Generated by Django 4.2.7 on 2024-09-04 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0005_todolist_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolist',
            name='notification_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
